### ISSUE TITLE
Bug in QR Code display

### ISSUE THREAD

**Issue by acrepet** [Dev-Mind/numeric-wall#88]
it's impossible to display big qr code:
15:17:39 [http-nio-8080-exec-8] WARN  o.h.e.l.i.LoadContexts - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@64a51d4c<rs=com.mysql.jdbc.JDBC4ResultSet@30fa5232>
15:17:39 [http-nio-8080-exec-8] WARN  o.h.e.l.i.CollectionLoadContext - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [4] entries
15:17:39 [http-nio-8080-exec-8] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: could not execute query; nested exception is org.hibernate.exception.GenericJDBCException: could not execute query] with root cause
java.sql.SQLException: Value '^B22^A6^D3764^A6^Lagnes.crepet��^DB�chez la queue du wagon-taxi avec les pyjamas du fakir. (anonyme) (55 lettres)
Monsieur Jack, vous dactylographiez bien mieux que votre ami Wolf (s'utilisait dans l'arm�e suisse pour tester le clavier des t�l�scripteurs. Elle n'a pas d'accent car ceux-ci ne pouvaient pas se transmettre) (55)
Voix ambigu� d'un c�ur qui, au z�phyr, pr�f�re les jattes de kiwis. (anonyme) (53) (utilis�e comme phrase de d�monstration de certaines polices typographiques, dont celles de Windows, � partir de la version XP & Blackberry)
Mon pauvre z�bu ankylos� choque deux fois ton wagon jaune (anonyme) (48)
Le vif z�phyr jubile sur les kumquats du clown gracieux. (utilis� comme phrase de d�monstration des polices de caract�re sous les vieilles versions de Mac OS et dans Papyrus Gold) (46)
Zut ! Je crois que le chien Sambuca pr�f�re le whisky revigorant au doux porto. (remplace la pr�c�dente dans des versions plus r�centes) (64)
Voyez le brick g�ant que j'examine pr�s du wharf. (utilis� par l'UIT1) (39)
Portez ce vieux whisky au juge blond qui fume (Charles Triouleyre ?) (37), alexandrin classique n�utilisant qu�une seule fois chaque consonne
Buvez de ce whisky que le patron juge fameux. (anonyme) (36)
Grimpez quand ce whisky flatte vos bijoux (Chambaron) (35)^S0000-00-00 00:00:00 VALIDATED^A6^Lagnes.crepet^Lagnes.crepet^S2016-01-26 18:29:31$541796b4-df8c-4842-bc08-dbb92325856c^A0^A6^B33^S2016-01-26 18:30:34^B22�/
M0 0.5h7M8 0.5h5M14 0.5h3M19 0.5h1M22 0.5h3M26 0.5h7M0 1.5h1M6 1.5h1M9 1.5h3M15 1.5h4M20 1.5h4M26 1.5h1M32 1.5h1M0 2.5h1M2 2.5h3M6 2.5h1M8 2.5h2M15 2.5h1M17 2.5h3M23 2.5h1M26 2.5h1M28 2.5h3M32 2.5h1M0 3.5h1M2 3.5h3M6 3.5h1M8 3.5h1M10 3.5h1M13 3.5h2M16 3.5h2M19 3.5h2M22 3.5h1M26 3.5h1M28 3.5h3M32 3.5h1M0 4.5h1M2 4.5h3M6 4.5h1M11 4.5h1M16 4.5h1M18 4.5h1M20 4.5h2M23 4.5h1M26 4.5h1M28 4.5h3M32 4.5h1M0 5.5h1M6 5.5h1M8 5.5h1M12 5.5h2M18 5.5h2M22 5.5h1M24 5.5h1M26 5.5h1M32 5.5h1M0 6.5h7M8 6.5h1M10 6.5h1M12 6.5h1M14 6.5h1M16 6.5h1M18 6.5h1M20 6.5h1M22 6.5h1M24 6.5h1M26 6.5h7M8 7.5h3M17 7.5h1M19 7.5h4M24 7.5h1M1 8.5h1M3 8.5h1M5 8.5h4M11 8.5h2M16 8.5h1M20 8.5h2M23 8.5h5M29 8.5h2M32 8.5h1M9 9.5h1M11 9.5h4M16 9.5h1M20 9.5h1M24 9.5h4M31 9.5h2M1 10.5h1M6 10.5h2M9 10.5h2M14 10.5h2M17 10.5h1M19 10.5h1M22 10.5h1M24 10.5h1M26 10.5h3M30 10.5h1M32 10.5h1M0 11.5h4M7 11.5h1M11 11.5h2M15 11.5h3M19 11.5h1M21 11.5h1M24 11.5h2M28 11.5h2M32 11.5h1M0 12.5h1M2 12.5h1M4 12.5h3M12 12.5h2M16 12.5h1M19 12.5h1M21 12.5h1M23 12.5h1M25 12.5h2M29 12.5h1M0 13.5h2M5 13.5h1M10 13.5h5M17 13.5h1M19 13.5h1M22 13.5h1M24 13.5h3M28 13.5h1M31 13.5h2M3 14.5h1M6 14.5h1M8 14.5h1M17 14.5h1M20 14.5h1M23 14.5h1M25 14.5h2M30 14.5h2M2 15.5h4M7 15.5h1M9 15.5h2M13 15.5h1M16 15.5h1M21 15.5h4M26 15.5h1M28 15.5h1M31 15.5h1M2 16.5h2M6 16.5h1M10 16.5h3M15 16.5h1M17 16.5h1M19 16.5h6M26 16.5h1M28 16.5h1M31 16.5h1M0 17.5h1M2 17.5h2M5 17.5h1M7 17.5h2M12 17.5h2M15 17.5h1M18 17.5h1M20 17.5h1M23 17.5h3M27 17.5h1M29 17.5h1M31 17.5h1M0 18.5h3M4 18.5h1M6 18.5h1M8 18.5h4M15 18.5h1M17 18.5h1M26 18.5h1M30 18.5h3M7 19.5h1M9 19.5h1M12 19.5h1M14 19.5h1M17 19.5h3M21 19.5h3M26 19.5h2M1 20.5h1M4 20.5h1M6 20.5h1M8 20.5h1M12 20.5h1M14 20.5h3M18 20.5h1M20 20.5h5M31 20.5h1M1 21.5h3M10 21.5h1M14 21.5h4M25 21.5h3M30 21.5h3M0 22.5h3M5 22.5h2M8 22.5h4M13 22.5h2M18 22.5h2M26 22.5h2M32 22.5h1M1 23.5h2M9 23.5h3M13 23.5h1M16 23.5h2M21 23.5h2M24 23.5h1M26 23.5h1M29 23.5h1M32 23.5h1M0 24.5h1M2 24.5h2M5 24.5h2M9 24.5h1M14 24.5h1M16 24.5h4M21 24.5h1M24 24.5h5M31 24.5h1M8 25.5h2M11 25.5h1M14 25.5h2M18 25.5h3M22 25.5h3M28 25.5h2M31 25.5h2M0 26.5h7M8 26.5h3M12 26.5h1M16 26.5h3M20 26.5h2M24 26.5h1M26 26.5h1M28 26.5h4M0 27.5h1M6 27.5h1M8 27.5h3M15 27.5h3M19 27.5h4M24 27.5h1M28 27.5h1M0 28.5h1M2 28.5h3M6 28.5h1M11 28.5h5M19 28.5h4M24 28.5h6M32 28.5h1M0 29.5h1M2 29.5h3M6 29.5h1M8 29.5h2M11 29.5h1M15 29.5h2M18 29.5h1M20 29.5h1M22 29.5h3M26 29.5h1M28 29.5h4M0 30.5h1M2 30.5h3M6 30.5h1M12 30.5h1M15 30.5h2M20 30.5h2M23 30.5h3M28 30.5h1M32 30.5h1M0 31.5h1M6 31.5h1M8 31.5h1M13 31.5h1M17 31.5h1M20 31.5h7M0 32.5h7M12 32.5h2M15 32.5h2M21 32.5h1M24 32.5h3M28 32.5h2M31 32.5h1-https://ewall.mines-stetienne.fr/e-wall/t/374^B24^A3^B22^D3764^At^S2016-01-26 18:30:33^MTerritoire(s)^AF^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@' can not be represented as java.sql.Timestamp
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:935) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.BufferRow.getTimestampFast(BufferRow.java:555) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]
        at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:5956) ~[mysql-connector-java-5.1.36.jar!/:5.1.36]

**Comment by acrepet** [comment]
and it's impossible to display the production in admin... hahaahahahh!

**Comment by acrepet** [comment]
after reading the log and the data, I find a row in Production with a creatdat="0000-00-00 00:00:00", I updated this colomn and after it's OK : the display of theb ig QRCode is OK and the display of the list of productions in admin is OK. Strange, no?

**Comment by javamind** [comment]
Pour la date de création elle est mise à jour en Java à la création de l'objet et ne change plus après. Donc oui plus que bizarre
